[versions]
managed-jaxrs-api = "3.1.0"

groovy = "4.0.18"
spock = "2.3-groovy-4.0"

micronaut = "4.5.3"
micronaut-docs = "2.0.0"
micronaut-test = "4.2.1"
micronaut-logging = "1.3.0"
micronaut-security = "4.9.0"
micronaut-serde = "2.10.1"
micronaut-servlet = "4.9.1"
micronaut-validation = "4.6.0"

jakarta-jaxrs-tck = "4.0.0"

[libraries]

micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-security = { module = "io.micronaut.security:micronaut-security-bom", version.ref = "micronaut-security" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-servlet = { module = "io.micronaut.servlet:micronaut-servlet-bom", version.ref = "micronaut-servlet" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-jaxrs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "managed-jaxrs-api" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine" }

jakarta-jaxrs-tck-tests = { module = 'jakarta.ws.rs:jakarta-restful-ws-tck', version.ref = "jakarta-jaxrs-tck" }
