[versions]
micronaut = "4.0.0-M2"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.0-M1"
groovy = "4.0.11"
spock = "2.3-groovy-4.0"
managed-jaxrs-api = "3.1.0"

micronaut-security = "4.0.0-M1"
micronaut-serde = "2.0.0-M1"
micronaut-validation = "4.0.0-M4"

[libraries]
managed-jaxrs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "managed-jaxrs-api" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

micronaut-security = { module = "io.micronaut.security:micronaut-security-bom", version.ref = "micronaut-security" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
