[versions]
micronaut = "4.1.3"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.0"
groovy = "4.0.13"
spock = "2.3-groovy-4.0"
managed-jaxrs-api = "3.1.0"

micronaut-logging = "1.1.0"
micronaut-security = "4.1.0"
micronaut-serde = "2.2.6"
micronaut-validation = "4.0.3"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-jaxrs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "managed-jaxrs-api" }

junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }

micronaut-security = { module = "io.micronaut.security:micronaut-security-bom", version.ref = "micronaut-security" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
